# Generated by Django 4.2.6 on 2023-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_de_perfil',
            field=models.ImageField(default='user.webp', upload_to='fotosPerfiles/'),
        ),
    ]
