# Generated by Django 4.2.6 on 2023-10-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventoAdmin', '0002_evento_hora_evento_nombre_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_persona',
            new_name='nombre',
        ),
    ]
