# Generated by Django 4.2.6 on 2023-10-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventoAdmin', '0003_rename_nombre_persona_evento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
